config:
  env: dev
  GracefulTimeout: 5
  rest:
    host: localhost
    port: 8080
  Upload:
    BaseUrl: https://d2pap2axpvlqe3.cloudfront.net/public/
    S3Bucket: hsaquibs3
    Folder: public
  APIs:
    AuthApi: https://auth-iamrz1.cloud.okteto.net/
